import {type NextPage} from "next";
import Head from "next/head";
import {signIn, signOut, useSession} from "next-auth/react";
import {api} from "n/utils/api";
import {SignInButton, SignOutButton, useUser} from "@clerk/nextjs";

const Home: NextPage = () => {
    const {data} = api.posts.getAll.useQuery()

    const user = useUser()

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className="flex justify-center">
                <div>
                    {!user.isSignedIn && (<SignInButton/>)}
                    {!!user.isSignedIn && (<SignOutButton/>)}
                </div>
                <div className="w-full h-full">
                    {
                        data?.map((post) => {
                            return(
                                <div key={post.id} className="bg-green">
                                    <h1 className="text-white">{post.content}</h1>

                                </div>
                            )
                        })
                    }
                </div>


            </main>
        </>
    );
};

export default Home;

const AuthShowcase: React.FC = () => {
    const {data: sessionData} = useSession();


    return (
        <div className="flex flex-col items-center justify-center gap-4">
            <p className="text-center text-2xl text-white">
                {sessionData && <span>Logged in as {sessionData.user?.name}</span>}

            </p>
            <button
                className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
                onClick={sessionData ? () => void signOut() : () => void signIn()}
            >
                {sessionData ? "Sign out" : "Sign in"}
            </button>
        </div>
    );
};
